version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: restaurant_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:password123}
      POSTGRES_DB: ${POSTGRES_DB:restaurant_orders}
      DB_HOST: ${DB_HOST:localhost}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-restaurant_orders}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
